# Generated by Django 5.1.6 on 2025-02-14 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anuncio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('categoria', models.CharField(choices=[('Trator', 'Trator'), ('Colheitadeira', 'Colheitadeira'), ('Caminhão', 'Caminhão'), ('Outros', 'Outros')], max_length=20)),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('ano', models.IntegerField()),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='imagens_anuncios/')),
                ('data_publicacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
