# Generated by Django 5.1.6 on 2025-02-19 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='anuncio',
            name='telefone_contato',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
