# Generated by Django 5.1.6 on 2025-02-20 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_anuncio_telefone_contato'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anuncio',
            name='imagem',
        ),
        migrations.CreateModel(
            name='ImagemAnuncio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='imagens_anuncios/')),
                ('anuncio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='home.anuncio')),
            ],
        ),
    ]
